fix: api

diff --git a/admin/Dockerfile b/admin/Dockerfile
--- a/admin/Dockerfile
+++ b/admin/Dockerfile
@@ -8,10 +8,14 @@ RUN npm install
 
 COPY . .
 
+# Run the build process
 RUN npm run build
 
-# Correct the source directory if needed
-COPY ./build ./public
+# Debugging: list the contents of the /app directory to see if build was successful
+RUN ls -la /app
+
+# Copy the build directory to public if it exists
+RUN if [ -d "./build" ]; then cp -r ./build ./public; else echo "Build directory not found"; exit 1; fi
 
 RUN chmod +x node_modules/.bin/react-scripts
 
